const express = require("express");
const cors = require("cors");

const app = express();
const PORT = 3000;

// CORS configuration
const corsOptions = {
  origin: "http://localhost:3000", // frontend site URL
  credentials: true,
  methods: ["GET", "POST", "PUT", "DELETE", "PATCH"],
  allowedHeaders: ["Content-Type", "Authorization"]
};

// Apply CORS middleware
app.use(cors(corsOptions));

// Middleware to parse JSON
app.use(express.json());

// Sample GET API
app.get("/", (req, res) => {
  res.send("API is running 🚀");
});

// GET all users
app.get("/users", (req, res) => {
  const users = 
 [
    {
      "pnr_number": "PNR100000",
      "name": "Amit Roy",
      "age": 31,
      "address": "Kolkata, India",
      "train_name": "Vande Bharat",
      "destination_station": "Mumbai Central",
      "journey_date": "2026-04-01",
      "seat_number": "S1-1",
      "coach": "S1",
      "status": "Confirmed"
    },
    {
      "pnr_number": "PNR100001",
      "name": "Sneha Ghosh",
      "age": 47,
      "address": "Chennai, India",
      "train_name": "Shatabdi Express",
      "destination_station": "Chennai Central",
      "journey_date": "2026-04-02",
      "seat_number": "S2-2",
      "coach": "S2",
      "status": "Waiting"
    },
    {
      "pnr_number": "PNR100002",
      "name": "Muskan Menon",
      "age": 31,
      "address": "Jaipur, India",
      "train_name": "Duronto Express",
      "destination_station": "New Delhi",
      "journey_date": "2026-04-03",
      "seat_number": "S3-3",
      "coach": "S3",
      "status": "Confirmed"
    },
    {
      "pnr_number": "PNR100003",
      "name": "Siddharth Nair",
      "age": 63,
      "address": "Patna, India",
      "train_name": "Vande Bharat",
      "destination_station": "Mumbai Central",
      "journey_date": "2026-04-04",
      "seat_number": "S4-4",
      "coach": "S4",
      "status": "RAC"
    },
    {
      "pnr_number": "PNR100004",
      "name": "Ishita Yadav",
      "age": 18,
      "address": "Jaipur, India",
      "train_name": "Duronto Express",
      "destination_station": "Bangalore City",
      "journey_date": "2026-04-05",
      "seat_number": "S5-5",
      "coach": "S5",
      "status": "Confirmed"
    },
    {
      "pnr_number": "PNR100005",
      "name": "Payal Gupta",
      "age": 59,
      "address": "Bangalore, India",
      "train_name": "Vande Bharat",
      "destination_station": "Bangalore City",
      "journey_date": "2026-04-06",
      "seat_number": "S1-6",
      "coach": "S1",
      "status": "Confirmed"
    },
    {
      "pnr_number": "PNR100006",
      "name": "Vihaan Chauhan",
      "age": 44,
      "address": "Ahmedabad, India",
      "train_name": "Garib Rath",
      "destination_station": "Chennai Central",
      "journey_date": "2026-04-07",
      "seat_number": "S2-7",
      "coach": "S2",
      "status": "Waiting"
    },
    {
      "pnr_number": "PNR100007",
      "name": "Rudra Ghosh",
      "age": 36,
      "address": "Mumbai, India",
      "train_name": "Vande Bharat",
      "destination_station": "Bangalore City",
      "journey_date": "2026-04-08",
      "seat_number": "S3-8",
      "coach": "S3",
      "status": "Confirmed"
    },
    {
      "pnr_number": "PNR100008",
      "name": "Ananya Patel",
      "age": 27,
      "address": "Patna, India",
      "train_name": "Garib Rath",
      "destination_station": "Bangalore City",
      "journey_date": "2026-04-09",
      "seat_number": "S4-9",
      "coach": "S4",
      "status": "RAC"
    },
    {
      "pnr_number": "PNR100009",
      "name": "Dhruv Banerjee",
      "age": 21,
      "address": "Lucknow, India",
      "train_name": "Rajdhani Express",
      "destination_station": "Mumbai Central",
      "journey_date": "2026-04-10",
      "seat_number": "S5-10",
      "coach": "S5",
      "status": "RAC"
    },
    {
      "pnr_number": "PNR100010",
      "name": "Nikhil Sharma",
      "age": 42,
      "address": "Bangalore, India",
      "train_name": "Shatabdi Express",
      "destination_station": "Howrah",
      "journey_date": "2026-04-01",
      "seat_number": "S1-11",
      "coach": "S1",
      "status": "RAC"
    },
    {
      "pnr_number": "PNR100011",
      "name": "Sai Patel",
      "age": 32,
      "address": "Ahmedabad, India",
      "train_name": "Rajdhani Express",
      "destination_station": "Mumbai Central",
      "journey_date": "2026-04-02",
      "seat_number": "S2-12",
      "coach": "S2",
      "status": "RAC"
    },
    {
      "pnr_number": "PNR100012",
      "name": "Meera Mishra",
      "age": 49,
      "address": "Jaipur, India",
      "train_name": "Garib Rath",
      "destination_station": "Chennai Central",
      "journey_date": "2026-04-03",
      "seat_number": "S3-13",
      "coach": "S3",
      "status": "RAC"
    },
    {
      "pnr_number": "PNR100013",
      "name": "Amit Reddy",
      "age": 57,
      "address": "Chennai, India",
      "train_name": "Garib Rath",
      "destination_station": "Mumbai Central",
      "journey_date": "2026-04-04",
      "seat_number": "S4-14",
      "coach": "S4",
      "status": "Confirmed"
    },
    {
      "pnr_number": "PNR100014",
      "name": "Arnav Sharma",
      "age": 18,
      "address": "Lucknow, India",
      "train_name": "Duronto Express",
      "destination_station": "Mumbai Central",
      "journey_date": "2026-04-05",
      "seat_number": "S5-15",
      "coach": "S5",
      "status": "RAC"
    },
    {
      "pnr_number": "PNR100015",
      "name": "Ishita Banerjee",
      "age": 20,
      "address": "Jaipur, India",
      "train_name": "Duronto Express",
      "destination_station": "Howrah",
      "journey_date": "2026-04-06",
      "seat_number": "S1-16",
      "coach": "S1",
      "status": "Confirmed"
    },
    {
      "pnr_number": "PNR100016",
      "name": "Payal Verma",
      "age": 55,
      "address": "Lucknow, India",
      "train_name": "Vande Bharat",
      "destination_station": "Chennai Central",
      "journey_date": "2026-04-07",
      "seat_number": "S2-17",
      "coach": "S2",
      "status": "Waiting"
    },
    {
      "pnr_number": "PNR100017",
      "name": "Siddharth Tiwari",
      "age": 59,
      "address": "Mumbai, India",
      "train_name": "Vande Bharat",
      "destination_station": "Bangalore City",
      "journey_date": "2026-04-08",
      "seat_number": "S3-18",
      "coach": "S3",
      "status": "Confirmed"
    },
    {
      "pnr_number": "PNR100018",
      "name": "Aryan Yadav",
      "age": 55,
      "address": "Delhi, India",
      "train_name": "Vande Bharat",
      "destination_station": "Mumbai Central",
      "journey_date": "2026-04-09",
      "seat_number": "S4-19",
      "coach": "S4",
      "status": "Waiting"
    },
    {
      "pnr_number": "PNR100019",
      "name": "Samar Mishra",
      "age": 54,
      "address": "Delhi, India",
      "train_name": "Vande Bharat",
      "destination_station": "Mumbai Central",
      "journey_date": "2026-04-10",
      "seat_number": "S5-20",
      "coach": "S5",
      "status": "RAC"
    },
    {
      "pnr_number": "PNR100020",
      "name": "Payal Reddy",
      "age": 38,
      "address": "Jaipur, India",
      "train_name": "Vande Bharat",
      "destination_station": "Howrah",
      "journey_date": "2026-04-01",
      "seat_number": "S1-21",
      "coach": "S1",
      "status": "Confirmed"
    },
    {
      "pnr_number": "PNR100021",
      "name": "Simran Nair",
      "age": 29,
      "address": "Mumbai, India",
      "train_name": "Shatabdi Express",
      "destination_station": "Chennai Central",
      "journey_date": "2026-04-02",
      "seat_number": "S2-22",
      "coach": "S2",
      "status": "Confirmed"
    },
    {
      "pnr_number": "PNR100022",
      "name": "Amit Kumar",
      "age": 44,
      "address": "Jaipur, India",
      "train_name": "Vande Bharat",
      "destination_station": "Howrah",
      "journey_date": "2026-04-03",
      "seat_number": "S3-23",
      "coach": "S3",
      "status": "Waiting"
    },
    {
      "pnr_number": "PNR100023",
      "name": "Arnav Yadav",
      "age": 62,
      "address": "Jaipur, India",
      "train_name": "Garib Rath",
      "destination_station": "Howrah",
      "journey_date": "2026-04-04",
      "seat_number": "S4-24",
      "coach": "S4",
      "status": "Waiting"
    },
    {
      "pnr_number": "PNR100024",
      "name": "Arnav Kumar",
      "age": 49,
      "address": "Mumbai, India",
      "train_name": "Rajdhani Express",
      "destination_station": "Howrah",
      "journey_date": "2026-04-05",
      "seat_number": "S5-25",
      "coach": "S5",
      "status": "Waiting"
    },
    {
      "pnr_number": "PNR100025",
      "name": "Tanvi Menon",
      "age": 58,
      "address": "Jaipur, India",
      "train_name": "Vande Bharat",
      "destination_station": "Chennai Central",
      "journey_date": "2026-04-06",
      "seat_number": "S1-26",
      "coach": "S1",
      "status": "Waiting"
    },
    {
      "pnr_number": "PNR100026",
      "name": "Anjali Das",
      "age": 53,
      "address": "Ahmedabad, India",
      "train_name": "Garib Rath",
      "destination_station": "New Delhi",
      "journey_date": "2026-04-07",
      "seat_number": "S2-27",
      "coach": "S2",
      "status": "Waiting"
    },
    {
      "pnr_number": "PNR100027",
      "name": "Anjali Patel",
      "age": 37,
      "address": "Jaipur, India",
      "train_name": "Garib Rath",
      "destination_station": "New Delhi",
      "journey_date": "2026-04-08",
      "seat_number": "S3-28",
      "coach": "S3",
      "status": "Waiting"
    },
    {
      "pnr_number": "PNR100028",
      "name": "Aarav Sharma",
      "age": 57,
      "address": "Pune, India",
      "train_name": "Duronto Express",
      "destination_station": "Chennai Central",
      "journey_date": "2026-04-09",
      "seat_number": "S4-29",
      "coach": "S4",
      "status": "RAC"
    },
    {
      "pnr_number": "PNR100029",
      "name": "Atharv Kumar",
      "age": 21,
      "address": "Lucknow, India",
      "train_name": "Shatabdi Express",
      "destination_station": "Howrah",
      "journey_date": "2026-04-10",
      "seat_number": "S5-30",
      "coach": "S5",
      "status": "Waiting"
    },
    {
      "pnr_number": "PNR100030",
      "name": "Nisha Roy",
      "age": 58,
      "address": "Mumbai, India",
      "train_name": "Shatabdi Express",
      "destination_station": "Bangalore City",
      "journey_date": "2026-04-01",
      "seat_number": "S1-31",
      "coach": "S1",
      "status": "Confirmed"
    },
    {
      "pnr_number": "PNR100031",
      "name": "Vedant Kumar",
      "age": 46,
      "address": "Chennai, India",
      "train_name": "Garib Rath",
      "destination_station": "Mumbai Central",
      "journey_date": "2026-04-02",
      "seat_number": "S2-32",
      "coach": "S2",
      "status": "Waiting"
    },
    {
      "pnr_number": "PNR100032",
      "name": "Aditya Mishra",
      "age": 57,
      "address": "Chennai, India",
      "train_name": "Shatabdi Express",
      "destination_station": "Mumbai Central",
      "journey_date": "2026-04-03",
      "seat_number": "S3-33",
      "coach": "S3",
      "status": "Waiting"
    },
    {
      "pnr_number": "PNR100033",
      "name": "Komal Verma",
      "age": 18,
      "address": "Patna, India",
      "train_name": "Garib Rath",
      "destination_station": "New Delhi",
      "journey_date": "2026-04-04",
      "seat_number": "S4-34",
      "coach": "S4",
      "status": "Confirmed"
    },
    {
      "pnr_number": "PNR100034",
      "name": "Swati Ghosh",
      "age": 18,
      "address": "Pune, India",
      "train_name": "Vande Bharat",
      "destination_station": "New Delhi",
      "journey_date": "2026-04-05",
      "seat_number": "S5-35",
      "coach": "S5",
      "status": "Waiting"
    },
    {
      "pnr_number": "PNR100035",
      "name": "Pooja Mishra",
      "age": 18,
      "address": "Delhi, India",
      "train_name": "Rajdhani Express",
      "destination_station": "Bangalore City",
      "journey_date": "2026-04-06",
      "seat_number": "S1-36",
      "coach": "S1",
      "status": "Waiting"
    },
    {
      "pnr_number": "PNR100036",
      "name": "Kartik Verma",
      "age": 61,
      "address": "Ahmedabad, India",
      "train_name": "Shatabdi Express",
      "destination_station": "Chennai Central",
      "journey_date": "2026-04-07",
      "seat_number": "S2-37",
      "coach": "S2",
      "status": "Waiting"
    },
    {
      "pnr_number": "PNR100037",
      "name": "Yash Reddy",
      "age": 41,
      "address": "Jaipur, India",
      "train_name": "Garib Rath",
      "destination_station": "New Delhi",
      "journey_date": "2026-04-08",
      "seat_number": "S3-38",
      "coach": "S3",
      "status": "Confirmed"
    },
    {
      "pnr_number": "PNR100038",
      "name": "Sneha Pandey",
      "age": 56,
      "address": "Mumbai, India",
      "train_name": "Shatabdi Express",
      "destination_station": "Howrah",
      "journey_date": "2026-04-09",
      "seat_number": "S4-39",
      "coach": "S4",
      "status": "RAC"
    },
    {
      "pnr_number": "PNR100039",
      "name": "Anjali Menon",
      "age": 27,
      "address": "Chennai, India",
      "train_name": "Vande Bharat",
      "destination_station": "Bangalore City",
      "journey_date": "2026-04-10",
      "seat_number": "S5-40",
      "coach": "S5",
      "status": "Confirmed"
    },
    {
      "pnr_number": "PNR100040",
      "name": "Aryan Roy",
      "age": 63,
      "address": "Pune, India",
      "train_name": "Duronto Express",
      "destination_station": "Chennai Central",
      "journey_date": "2026-04-01",
      "seat_number": "S1-41",
      "coach": "S1",
      "status": "Waiting"
    },
    {
      "pnr_number": "PNR100041",
      "name": "Muskan Sharma",
      "age": 34,
      "address": "Chennai, India",
      "train_name": "Duronto Express",
      "destination_station": "Bangalore City",
      "journey_date": "2026-04-02",
      "seat_number": "S2-42",
      "coach": "S2",
      "status": "Confirmed"
    },
    {
      "pnr_number": "PNR100042",
      "name": "Tanvi Kumar",
      "age": 59,
      "address": "Lucknow, India",
      "train_name": "Rajdhani Express",
      "destination_station": "New Delhi",
      "journey_date": "2026-04-03",
      "seat_number": "S3-43",
      "coach": "S3",
      "status": "Confirmed"
    },
    {
      "pnr_number": "PNR100043",
      "name": "Meera Sharma",
      "age": 40,
      "address": "Delhi, India",
      "train_name": "Vande Bharat",
      "destination_station": "Mumbai Central",
      "journey_date": "2026-04-04",
      "seat_number": "S4-44",
      "coach": "S4",
      "status": "RAC"
    },
    {
      "pnr_number": "PNR100044",
      "name": "Neha Tiwari",
      "age": 65,
      "address": "Bangalore, India",
      "train_name": "Shatabdi Express",
      "destination_station": "Howrah",
      "journey_date": "2026-04-05",
      "seat_number": "S5-45",
      "coach": "S5",
      "status": "Confirmed"
    },
    {
      "pnr_number": "PNR100045",
      "name": "Manav Chauhan",
      "age": 65,
      "address": "Ahmedabad, India",
      "train_name": "Garib Rath",
      "destination_station": "Howrah",
      "journey_date": "2026-04-06",
      "seat_number": "S1-46",
      "coach": "S1",
      "status": "Confirmed"
    },
    {
      "pnr_number": "PNR100046",
      "name": "Yash Kumar",
      "age": 42,
      "address": "Mumbai, India",
      "train_name": "Shatabdi Express",
      "destination_station": "New Delhi",
      "journey_date": "2026-04-07",
      "seat_number": "S2-47",
      "coach": "S2",
      "status": "RAC"
    },
    {
      "pnr_number": "PNR100047",
      "name": "Sneha Singh",
      "age": 39,
      "address": "Lucknow, India",
      "train_name": "Garib Rath",
      "destination_station": "New Delhi",
      "journey_date": "2026-04-08",
      "seat_number": "S3-48",
      "coach": "S3",
      "status": "RAC"
    },
    {
      "pnr_number": "PNR100048",
      "name": "Aanya Ghosh",
      "age": 45,
      "address": "Pune, India",
      "train_name": "Duronto Express",
      "destination_station": "Howrah",
      "journey_date": "2026-04-09",
      "seat_number": "S4-49",
      "coach": "S4",
      "status": "Waiting"
    },
    {
      "pnr_number": "PNR100049",
      "name": "Rudra Gupta",
      "age": 55,
      "address": "Bangalore, India",
      "train_name": "Rajdhani Express",
      "destination_station": "Mumbai Central",
      "journey_date": "2026-04-10",
      "seat_number": "S5-50",
      "coach": "S5",
      "status": "Waiting"
    },
    {
      "pnr_number": "PNR100050",
      "name": "Vedant Singh",
      "age": 25,
      "address": "Bangalore, India",
      "train_name": "Vande Bharat",
      "destination_station": "New Delhi",
      "journey_date": "2026-04-01",
      "seat_number": "S1-51",
      "coach": "S1",
      "status": "Waiting"
    },
    {
      "pnr_number": "PNR100051",
      "name": "Kavya Reddy",
      "age": 37,
      "address": "Pune, India",
      "train_name": "Shatabdi Express",
      "destination_station": "Chennai Central",
      "journey_date": "2026-04-02",
      "seat_number": "S2-52",
      "coach": "S2",
      "status": "RAC"
    },
    {
      "pnr_number": "PNR100052",
      "name": "Siddharth Patel",
      "age": 63,
      "address": "Chennai, India",
      "train_name": "Shatabdi Express",
      "destination_station": "Chennai Central",
      "journey_date": "2026-04-03",
      "seat_number": "S3-53",
      "coach": "S3",
      "status": "RAC"
    },
    {
      "pnr_number": "PNR100053",
      "name": "Sneha Jain",
      "age": 39,
      "address": "Delhi, India",
      "train_name": "Duronto Express",
      "destination_station": "Chennai Central",
      "journey_date": "2026-04-04",
      "seat_number": "S4-54",
      "coach": "S4",
      "status": "RAC"
    },
    {
      "pnr_number": "PNR100054",
      "name": "Yash Pandey",
      "age": 24,
      "address": "Mumbai, India",
      "train_name": "Shatabdi Express",
      "destination_station": "New Delhi",
      "journey_date": "2026-04-05",
      "seat_number": "S5-55",
      "coach": "S5",
      "status": "RAC"
    },
    {
      "pnr_number": "PNR100055",
      "name": "Aryan Chauhan",
      "age": 40,
      "address": "Patna, India",
      "train_name": "Shatabdi Express",
      "destination_station": "Chennai Central",
      "journey_date": "2026-04-06",
      "seat_number": "S1-56",
      "coach": "S1",
      "status": "Waiting"
    },
    {
      "pnr_number": "PNR100056",
      "name": "Manav Agarwal",
      "age": 30,
      "address": "Patna, India",
      "train_name": "Shatabdi Express",
      "destination_station": "Chennai Central",
      "journey_date": "2026-04-07",
      "seat_number": "S2-57",
      "coach": "S2",
      "status": "RAC"
    },
    {
      "pnr_number": "PNR100057",
      "name": "Aryan Pandey",
      "age": 33,
      "address": "Mumbai, India",
      "train_name": "Vande Bharat",
      "destination_station": "Howrah",
      "journey_date": "2026-04-08",
      "seat_number": "S3-58",
      "coach": "S3",
      "status": "Waiting"
    },
    {
      "pnr_number": "PNR100058",
      "name": "Samar Mishra",
      "age": 47,
      "address": "Chennai, India",
      "train_name": "Vande Bharat",
      "destination_station": "Chennai Central",
      "journey_date": "2026-04-09",
      "seat_number": "S4-59",
      "coach": "S4",
      "status": "RAC"
    },
    {
      "pnr_number": "PNR100059",
      "name": "Pooja Roy",
      "age": 46,
      "address": "Mumbai, India",
      "train_name": "Duronto Express",
      "destination_station": "Chennai Central",
      "journey_date": "2026-04-10",
      "seat_number": "S5-60",
      "coach": "S5",
      "status": "Waiting"
    },
    {
      "pnr_number": "PNR100060",
      "name": "Diya Patel",
      "age": 35,
      "address": "Pune, India",
      "train_name": "Duronto Express",
      "destination_station": "Chennai Central",
      "journey_date": "2026-04-01",
      "seat_number": "S1-61",
      "coach": "S1",
      "status": "Waiting"
    },
    {
      "pnr_number": "PNR100061",
      "name": "Ishita Menon",
      "age": 51,
      "address": "Bangalore, India",
      "train_name": "Shatabdi Express",
      "destination_station": "New Delhi",
      "journey_date": "2026-04-02",
      "seat_number": "S2-62",
      "coach": "S2",
      "status": "RAC"
    },
    {
      "pnr_number": "PNR100062",
      "name": "Parth Gupta",
      "age": 21,
      "address": "Kolkata, India",
      "train_name": "Duronto Express",
      "destination_station": "Howrah",
      "journey_date": "2026-04-03",
      "seat_number": "S3-63",
      "coach": "S3",
      "status": "Waiting"
    },
    {
      "pnr_number": "PNR100063",
      "name": "Komal Chauhan",
      "age": 39,
      "address": "Lucknow, India",
      "train_name": "Vande Bharat",
      "destination_station": "Bangalore City",
      "journey_date": "2026-04-04",
      "seat_number": "S4-64",
      "coach": "S4",
      "status": "Waiting"
    },
    {
      "pnr_number": "PNR100064",
      "name": "Sai Menon",
      "age": 45,
      "address": "Chennai, India",
      "train_name": "Rajdhani Express",
      "destination_station": "Chennai Central",
      "journey_date": "2026-04-05",
      "seat_number": "S5-65",
      "coach": "S5",
      "status": "Waiting"
    },
    {
      "pnr_number": "PNR100065",
      "name": "Kabir Agarwal",
      "age": 49,
      "address": "Kolkata, India",
      "train_name": "Vande Bharat",
      "destination_station": "Howrah",
      "journey_date": "2026-04-06",
      "seat_number": "S1-66",
      "coach": "S1",
      "status": "Confirmed"
    },
    {
      "pnr_number": "PNR100066",
      "name": "Anjali Singh",
      "age": 36,
      "address": "Pune, India",
      "train_name": "Shatabdi Express",
      "destination_station": "Bangalore City",
      "journey_date": "2026-04-07",
      "seat_number": "S2-67",
      "coach": "S2",
      "status": "RAC"
    },
    {
      "pnr_number": "PNR100067",
      "name": "Vihaan Menon",
      "age": 31,
      "address": "Mumbai, India",
      "train_name": "Shatabdi Express",
      "destination_station": "Mumbai Central",
      "journey_date": "2026-04-08",
      "seat_number": "S3-68",
      "coach": "S3",
      "status": "RAC"
    },
    {
      "pnr_number": "PNR100068",
      "name": "Swati Ghosh",
      "age": 21,
      "address": "Mumbai, India",
      "train_name": "Shatabdi Express",
      "destination_station": "Chennai Central",
      "journey_date": "2026-04-09",
      "seat_number": "S4-69",
      "coach": "S4",
      "status": "RAC"
    },
    {
      "pnr_number": "PNR100069",
      "name": "Tanvi Pandey",
      "age": 55,
      "address": "Jaipur, India",
      "train_name": "Rajdhani Express",
      "destination_station": "Chennai Central",
      "journey_date": "2026-04-10",
      "seat_number": "S5-70",
      "coach": "S5",
      "status": "Confirmed"
    },
    {
      "pnr_number": "PNR100070",
      "name": "Muhammad Chauhan",
      "age": 55,
      "address": "Patna, India",
      "train_name": "Garib Rath",
      "destination_station": "New Delhi",
      "journey_date": "2026-04-01",
      "seat_number": "S1-71",
      "coach": "S1",
      "status": "Waiting"
    },
    {
      "pnr_number": "PNR100071",
      "name": "Swati Roy",
      "age": 35,
      "address": "Patna, India",
      "train_name": "Garib Rath",
      "destination_station": "Howrah",
      "journey_date": "2026-04-02",
      "seat_number": "S2-72",
      "coach": "S2",
      "status": "Waiting"
    },
    {
      "pnr_number": "PNR100072",
      "name": "Komal Verma",
      "age": 27,
      "address": "Patna, India",
      "train_name": "Garib Rath",
      "destination_station": "Chennai Central",
      "journey_date": "2026-04-03",
      "seat_number": "S3-1",
      "coach": "S3",
      "status": "Waiting"
    },
    {
      "pnr_number": "PNR100073",
      "name": "Yash Banerjee",
      "age": 36,
      "address": "Lucknow, India",
      "train_name": "Shatabdi Express",
      "destination_station": "New Delhi",
      "journey_date": "2026-04-04",
      "seat_number": "S4-2",
      "coach": "S4",
      "status": "RAC"
    },
    {
      "pnr_number": "PNR100074",
      "name": "Payal Das",
      "age": 52,
      "address": "Pune, India",
      "train_name": "Vande Bharat",
      "destination_station": "Mumbai Central",
      "journey_date": "2026-04-05",
      "seat_number": "S5-3",
      "coach": "S5",
      "status": "RAC"
    },
    {
      "pnr_number": "PNR100075",
      "name": "Priya Verma",
      "age": 19,
      "address": "Mumbai, India",
      "train_name": "Rajdhani Express",
      "destination_station": "Howrah",
      "journey_date": "2026-04-06",
      "seat_number": "S1-4",
      "coach": "S1",
      "status": "RAC"
    },
    {
      "pnr_number": "PNR100076",
      "name": "Ayush Banerjee",
      "age": 51,
      "address": "Ahmedabad, India",
      "train_name": "Rajdhani Express",
      "destination_station": "New Delhi",
      "journey_date": "2026-04-07",
      "seat_number": "S2-5",
      "coach": "S2",
      "status": "RAC"
    },
    {
      "pnr_number": "PNR100077",
      "name": "Parth Agarwal",
      "age": 21,
      "address": "Ahmedabad, India",
      "train_name": "Vande Bharat",
      "destination_station": "New Delhi",
      "journey_date": "2026-04-08",
      "seat_number": "S3-6",
      "coach": "S3",
      "status": "Confirmed"
    },
    {
      "pnr_number": "PNR100078",
      "name": "Kabir Patel",
      "age": 36,
      "address": "Jaipur, India",
      "train_name": "Shatabdi Express",
      "destination_station": "Howrah",
      "journey_date": "2026-04-09",
      "seat_number": "S4-7",
      "coach": "S4",
      "status": "Confirmed"
    },
    {
      "pnr_number": "PNR100079",
      "name": "Muhammad Pandey",
      "age": 34,
      "address": "Mumbai, India",
      "train_name": "Rajdhani Express",
      "destination_station": "Mumbai Central",
      "journey_date": "2026-04-10",
      "seat_number": "S5-8",
      "coach": "S5",
      "status": "Waiting"
    },
    {
      "pnr_number": "PNR100080",
      "name": "Ayaan Kumar",
      "age": 60,
      "address": "Mumbai, India",
      "train_name": "Shatabdi Express",
      "destination_station": "Bangalore City",
      "journey_date": "2026-04-01",
      "seat_number": "S1-9",
      "coach": "S1",
      "status": "Waiting"
    },
    {
      "pnr_number": "PNR100081",
      "name": "Ishaan Nair",
      "age": 55,
      "address": "Lucknow, India",
      "train_name": "Duronto Express",
      "destination_station": "New Delhi",
      "journey_date": "2026-04-02",
      "seat_number": "S2-10",
      "coach": "S2",
      "status": "Confirmed"
    },
    {
      "pnr_number": "PNR100082",
      "name": "Anjali Singh",
      "age": 37,
      "address": "Jaipur, India",
      "train_name": "Shatabdi Express",
      "destination_station": "Chennai Central",
      "journey_date": "2026-04-03",
      "seat_number": "S3-11",
      "coach": "S3",
      "status": "Confirmed"
    },
    {
      "pnr_number": "PNR100083",
      "name": "Siddharth Gupta",
      "age": 29,
      "address": "Bangalore, India",
      "train_name": "Rajdhani Express",
      "destination_station": "Bangalore City",
      "journey_date": "2026-04-04",
      "seat_number": "S4-12",
      "coach": "S4",
      "status": "Confirmed"
    },
    {
      "pnr_number": "PNR100084",
      "name": "Vihaan Reddy",
      "age": 32,
      "address": "Delhi, India",
      "train_name": "Duronto Express",
      "destination_station": "Mumbai Central",
      "journey_date": "2026-04-05",
      "seat_number": "S5-13",
      "coach": "S5",
      "status": "Confirmed"
    },
    {
      "pnr_number": "PNR100085",
      "name": "Kabir Nair",
      "age": 24,
      "address": "Ahmedabad, India",
      "train_name": "Vande Bharat",
      "destination_station": "Bangalore City",
      "journey_date": "2026-04-06",
      "seat_number": "S1-14",
      "coach": "S1",
      "status": "RAC"
    },
    {
      "pnr_number": "PNR100086",
      "name": "Ayush Roy",
      "age": 20,
      "address": "Bangalore, India",
      "train_name": "Shatabdi Express",
      "destination_station": "Bangalore City",
      "journey_date": "2026-04-07",
      "seat_number": "S2-15",
      "coach": "S2",
      "status": "Waiting"
    },
    {
      "pnr_number": "PNR100087",
      "name": "Manav Tiwari",
      "age": 29,
      "address": "Lucknow, India",
      "train_name": "Garib Rath",
      "destination_station": "Bangalore City",
      "journey_date": "2026-04-08",
      "seat_number": "S3-16",
      "coach": "S3",
      "status": "RAC"
    },
    {
      "pnr_number": "PNR100088",
      "name": "Kartik Das",
      "age": 26,
      "address": "Pune, India",
      "train_name": "Garib Rath",
      "destination_station": "Howrah",
      "journey_date": "2026-04-09",
      "seat_number": "S4-17",
      "coach": "S4",
      "status": "RAC"
    },
    {
      "pnr_number": "PNR100089",
      "name": "Atharv Yadav",
      "age": 26,
      "address": "Bangalore, India",
      "train_name": "Rajdhani Express",
      "destination_station": "New Delhi",
      "journey_date": "2026-04-10",
      "seat_number": "S5-18",
      "coach": "S5",
      "status": "Waiting"
    },
    {
      "pnr_number": "PNR100090",
      "name": "Krishna Verma",
      "age": 41,
      "address": "Kolkata, India",
      "train_name": "Duronto Express",
      "destination_station": "Mumbai Central",
      "journey_date": "2026-04-01",
      "seat_number": "S1-19",
      "coach": "S1",
      "status": "Waiting"
    },
    {
      "pnr_number": "PNR100091",
      "name": "Parth Yadav",
      "age": 33,
      "address": "Delhi, India",
      "train_name": "Vande Bharat",
      "destination_station": "New Delhi",
      "journey_date": "2026-04-02",
      "seat_number": "S2-20",
      "coach": "S2",
      "status": "Confirmed"
    },
    {
      "pnr_number": "PNR100092",
      "name": "Shreya Das",
      "age": 42,
      "address": "Patna, India",
      "train_name": "Garib Rath",
      "destination_station": "New Delhi",
      "journey_date": "2026-04-03",
      "seat_number": "S3-21",
      "coach": "S3",
      "status": "Confirmed"
    },
    {
      "pnr_number": "PNR100093",
      "name": "Aditya Kumar",
      "age": 43,
      "address": "Mumbai, India",
      "train_name": "Duronto Express",
      "destination_station": "Mumbai Central",
      "journey_date": "2026-04-04",
      "seat_number": "S4-22",
      "coach": "S4",
      "status": "Waiting"
    },
    {
      "pnr_number": "PNR100094",
      "name": "Meera Mishra",
      "age": 54,
      "address": "Jaipur, India",
      "train_name": "Duronto Express",
      "destination_station": "Chennai Central",
      "journey_date": "2026-04-05",
      "seat_number": "S5-23",
      "coach": "S5",
      "status": "RAC"
    },
    {
      "pnr_number": "PNR100095",
      "name": "Atharv Singh",
      "age": 65,
      "address": "Chennai, India",
      "train_name": "Shatabdi Express",
      "destination_station": "New Delhi",
      "journey_date": "2026-04-06",
      "seat_number": "S1-24",
      "coach": "S1",
      "status": "Confirmed"
    },
    {
      "pnr_number": "PNR100096",
      "name": "Shaurya Yadav",
      "age": 35,
      "address": "Bangalore, India",
      "train_name": "Shatabdi Express",
      "destination_station": "Mumbai Central",
      "journey_date": "2026-04-07",
      "seat_number": "S2-25",
      "coach": "S2",
      "status": "Confirmed"
    },
    {
      "pnr_number": "PNR100097",
      "name": "Pooja Mishra",
      "age": 24,
      "address": "Lucknow, India",
      "train_name": "Shatabdi Express",
      "destination_station": "Chennai Central",
      "journey_date": "2026-04-08",
      "seat_number": "S3-26",
      "coach": "S3",
      "status": "Waiting"
    },
    {
      "pnr_number": "PNR100098",
      "name": "Priya Menon",
      "age": 39,
      "address": "Kolkata, India",
      "train_name": "Duronto Express",
      "destination_station": "Howrah",
      "journey_date": "2026-04-09",
      "seat_number": "S4-27",
      "coach": "S4",
      "status": "Waiting"
    },
    {
      "pnr_number": "PNR100099",
      "name": "Aditya Chauhan",
      "age": 32,
      "address": "Delhi, India",
      "train_name": "Garib Rath",
      "destination_station": "Howrah",
      "journey_date": "2026-04-10",
      "seat_number": "S5-28",
      "coach": "S5",
      "status": "Waiting"
    },
    {
      "pnr_number": "PNR100100",
      "name": "Rohan Singh",
      "age": 24,
      "address": "Chennai, India",
      "train_name": "Duronto Express",
      "destination_station": "Bangalore City",
      "journey_date": "2026-04-01",
      "seat_number": "S1-29",
      "coach": "S1",
      "status": "Confirmed"
    },
    {
      "pnr_number": "PNR100101",
      "name": "Meera Sharma",
      "age": 30,
      "address": "Ahmedabad, India",
      "train_name": "Duronto Express",
      "destination_station": "Chennai Central",
      "journey_date": "2026-04-02",
      "seat_number": "S2-30",
      "coach": "S2",
      "status": "Confirmed"
    },
    {
      "pnr_number": "PNR100102",
      "name": "Vedant Sharma",
      "age": 48,
      "address": "Pune, India",
      "train_name": "Shatabdi Express",
      "destination_station": "Mumbai Central",
      "journey_date": "2026-04-03",
      "seat_number": "S3-31",
      "coach": "S3",
      "status": "Waiting"
    },
    {
      "pnr_number": "PNR100103",
      "name": "Amit Banerjee",
      "age": 41,
      "address": "Bangalore, India",
      "train_name": "Duronto Express",
      "destination_station": "Bangalore City",
      "journey_date": "2026-04-04",
      "seat_number": "S4-32",
      "coach": "S4",
      "status": "Confirmed"
    },
    {
      "pnr_number": "PNR100104",
      "name": "Ananya Agarwal",
      "age": 35,
      "address": "Mumbai, India",
      "train_name": "Shatabdi Express",
      "destination_station": "Chennai Central",
      "journey_date": "2026-04-05",
      "seat_number": "S5-33",
      "coach": "S5",
      "status": "Confirmed"
    },
    {
      "pnr_number": "PNR100105",
      "name": "Kartik Singh",
      "age": 52,
      "address": "Kolkata, India",
      "train_name": "Duronto Express",
      "destination_station": "Bangalore City",
      "journey_date": "2026-04-06",
      "seat_number": "S1-34",
      "coach": "S1",
      "status": "Waiting"
    },
    {
      "pnr_number": "PNR100106",
      "name": "Neha Chauhan",
      "age": 47,
      "address": "Pune, India",
      "train_name": "Duronto Express",
      "destination_station": "Bangalore City",
      "journey_date": "2026-04-07",
      "seat_number": "S2-35",
      "coach": "S2",
      "status": "RAC"
    },
    {
      "pnr_number": "PNR100107",
      "name": "Vivaan Roy",
      "age": 43,
      "address": "Chennai, India",
      "train_name": "Rajdhani Express",
      "destination_station": "New Delhi",
      "journey_date": "2026-04-08",
      "seat_number": "S3-36",
      "coach": "S3",
      "status": "Confirmed"
    },
    {
      "pnr_number": "PNR100108",
      "name": "Siddharth Das",
      "age": 63,
      "address": "Mumbai, India",
      "train_name": "Garib Rath",
      "destination_station": "Howrah",
      "journey_date": "2026-04-09",
      "seat_number": "S4-37",
      "coach": "S4",
      "status": "Waiting"
    },
    {
      "pnr_number": "PNR100109",
      "name": "Payal Agarwal",
      "age": 29,
      "address": "Delhi, India",
      "train_name": "Rajdhani Express",
      "destination_station": "Bangalore City",
      "journey_date": "2026-04-10",
      "seat_number": "S5-38",
      "coach": "S5",
      "status": "RAC"
    },
    {
      "pnr_number": "PNR100110",
      "name": "Nisha Reddy",
      "age": 42,
      "address": "Patna, India",
      "train_name": "Vande Bharat",
      "destination_station": "Chennai Central",
      "journey_date": "2026-04-01",
      "seat_number": "S1-39",
      "coach": "S1",
      "status": "RAC"
    },
    {
      "pnr_number": "PNR100111",
      "name": "Meera Kumar",
      "age": 40,
      "address": "Delhi, India",
      "train_name": "Duronto Express",
      "destination_station": "New Delhi",
      "journey_date": "2026-04-02",
      "seat_number": "S2-40",
      "coach": "S2",
      "status": "RAC"
    },
    {
      "pnr_number": "PNR100112",
      "name": "Ayush Mishra",
      "age": 51,
      "address": "Bangalore, India",
      "train_name": "Vande Bharat",
      "destination_station": "Chennai Central",
      "journey_date": "2026-04-03",
      "seat_number": "S3-41",
      "coach": "S3",
      "status": "Waiting"
    },
    {
      "pnr_number": "PNR100113",
      "name": "Payal Sharma",
      "age": 24,
      "address": "Lucknow, India",
      "train_name": "Garib Rath",
      "destination_station": "Bangalore City",
      "journey_date": "2026-04-04",
      "seat_number": "S4-42",
      "coach": "S4",
      "status": "RAC"
    },
    {
      "pnr_number": "PNR100114",
      "name": "Parth Chauhan",
      "age": 43,
      "address": "Kolkata, India",
      "train_name": "Vande Bharat",
      "destination_station": "Howrah",
      "journey_date": "2026-04-05",
      "seat_number": "S5-43",
      "coach": "S5",
      "status": "Waiting"
    },
    {
      "pnr_number": "PNR100115",
      "name": "Swati Das",
      "age": 33,
      "address": "Kolkata, India",
      "train_name": "Garib Rath",
      "destination_station": "Howrah",
      "journey_date": "2026-04-06",
      "seat_number": "S1-44",
      "coach": "S1",
      "status": "RAC"
    },
    {
      "pnr_number": "PNR100116",
      "name": "Tanvi Mishra",
      "age": 42,
      "address": "Patna, India",
      "train_name": "Garib Rath",
      "destination_station": "Howrah",
      "journey_date": "2026-04-07",
      "seat_number": "S2-45",
      "coach": "S2",
      "status": "RAC"
    },
    {
      "pnr_number": "PNR100117",
      "name": "Rudra Sharma",
      "age": 53,
      "address": "Jaipur, India",
      "train_name": "Duronto Express",
      "destination_station": "New Delhi",
      "journey_date": "2026-04-08",
      "seat_number": "S3-46",
      "coach": "S3",
      "status": "RAC"
    },
    {
      "pnr_number": "PNR100118",
      "name": "Payal Pandey",
      "age": 20,
      "address": "Delhi, India",
      "train_name": "Shatabdi Express",
      "destination_station": "Mumbai Central",
      "journey_date": "2026-04-09",
      "seat_number": "S4-47",
      "coach": "S4",
      "status": "Waiting"
    },
    {
      "pnr_number": "PNR100119",
      "name": "Sai Jain",
      "age": 41,
      "address": "Pune, India",
      "train_name": "Rajdhani Express",
      "destination_station": "New Delhi",
      "journey_date": "2026-04-10",
      "seat_number": "S5-48",
      "coach": "S5",
      "status": "Waiting"
    },
    {
      "pnr_number": "PNR100120",
      "name": "Kartik Ghosh",
      "age": 20,
      "address": "Patna, India",
      "train_name": "Garib Rath",
      "destination_station": "Mumbai Central",
      "journey_date": "2026-04-01",
      "seat_number": "S1-49",
      "coach": "S1",
      "status": "Confirmed"
    },
    {
      "pnr_number": "PNR100121",
      "name": "Neha Gupta",
      "age": 19,
      "address": "Bangalore, India",
      "train_name": "Duronto Express",
      "destination_station": "Howrah",
      "journey_date": "2026-04-02",
      "seat_number": "S2-50",
      "coach": "S2",
      "status": "Confirmed"
    },
    {
      "pnr_number": "PNR100122",
      "name": "Ananya Mishra",
      "age": 28,
      "address": "Jaipur, India",
      "train_name": "Vande Bharat",
      "destination_station": "Chennai Central",
      "journey_date": "2026-04-03",
      "seat_number": "S3-51",
      "coach": "S3",
      "status": "Waiting"
    },
    {
      "pnr_number": "PNR100123",
      "name": "Aryan Gupta",
      "age": 27,
      "address": "Patna, India",
      "train_name": "Rajdhani Express",
      "destination_station": "Chennai Central",
      "journey_date": "2026-04-04",
      "seat_number": "S4-52",
      "coach": "S4",
      "status": "RAC"
    },
    {
      "pnr_number": "PNR100124",
      "name": "Siddharth Pandey",
      "age": 52,
      "address": "Mumbai, India",
      "train_name": "Duronto Express",
      "destination_station": "Bangalore City",
      "journey_date": "2026-04-05",
      "seat_number": "S5-53",
      "coach": "S5",
      "status": "RAC"
    },
    {
      "pnr_number": "PNR100125",
      "name": "Vihaan Pandey",
      "age": 24,
      "address": "Mumbai, India",
      "train_name": "Rajdhani Express",
      "destination_station": "Bangalore City",
      "journey_date": "2026-04-06",
      "seat_number": "S1-54",
      "coach": "S1",
      "status": "Waiting"
    },
    {
      "pnr_number": "PNR100126",
      "name": "Simran Chauhan",
      "age": 34,
      "address": "Delhi, India",
      "train_name": "Duronto Express",
      "destination_station": "Howrah",
      "journey_date": "2026-04-07",
      "seat_number": "S2-55",
      "coach": "S2",
      "status": "Waiting"
    },
    {
      "pnr_number": "PNR100127",
      "name": "Diya Singh",
      "age": 51,
      "address": "Lucknow, India",
      "train_name": "Garib Rath",
      "destination_station": "Bangalore City",
      "journey_date": "2026-04-08",
      "seat_number": "S3-56",
      "coach": "S3",
      "status": "Waiting"
    },
    {
      "pnr_number": "PNR100128",
      "name": "Arnav Jain",
      "age": 35,
      "address": "Bangalore, India",
      "train_name": "Vande Bharat",
      "destination_station": "Chennai Central",
      "journey_date": "2026-04-09",
      "seat_number": "S4-57",
      "coach": "S4",
      "status": "Waiting"
    },
    {
      "pnr_number": "PNR100129",
      "name": "Shreya Gupta",
      "age": 37,
      "address": "Ahmedabad, India",
      "train_name": "Garib Rath",
      "destination_station": "Mumbai Central",
      "journey_date": "2026-04-10",
      "seat_number": "S5-58",
      "coach": "S5",
      "status": "Confirmed"
    },
    {
      "pnr_number": "PNR100130",
      "name": "Ananya Yadav",
      "age": 27,
      "address": "Kolkata, India",
      "train_name": "Garib Rath",
      "destination_station": "Mumbai Central",
      "journey_date": "2026-04-01",
      "seat_number": "S1-59",
      "coach": "S1",
      "status": "Confirmed"
    },
    {
      "pnr_number": "PNR100131",
      "name": "Kabir Tiwari",
      "age": 34,
      "address": "Jaipur, India",
      "train_name": "Garib Rath",
      "destination_station": "New Delhi",
      "journey_date": "2026-04-02",
      "seat_number": "S2-60",
      "coach": "S2",
      "status": "Waiting"
    },
    {
      "pnr_number": "PNR100132",
      "name": "Vihaan Kumar",
      "age": 43,
      "address": "Delhi, India",
      "train_name": "Duronto Express",
      "destination_station": "Mumbai Central",
      "journey_date": "2026-04-03",
      "seat_number": "S3-61",
      "coach": "S3",
      "status": "Waiting"
    },
    {
      "pnr_number": "PNR100133",
      "name": "Rudra Patel",
      "age": 50,
      "address": "Bangalore, India",
      "train_name": "Rajdhani Express",
      "destination_station": "Howrah",
      "journey_date": "2026-04-04",
      "seat_number": "S4-62",
      "coach": "S4",
      "status": "RAC"
    },
    {
      "pnr_number": "PNR100134",
      "name": "Krishna Singh",
      "age": 19,
      "address": "Pune, India",
      "train_name": "Vande Bharat",
      "destination_station": "Mumbai Central",
      "journey_date": "2026-04-05",
      "seat_number": "S5-63",
      "coach": "S5",
      "status": "Waiting"
    },
    {
      "pnr_number": "PNR100135",
      "name": "Riya Singh",
      "age": 52,
      "address": "Bangalore, India",
      "train_name": "Rajdhani Express",
      "destination_station": "New Delhi",
      "journey_date": "2026-04-06",
      "seat_number": "S1-64",
      "coach": "S1",
      "status": "RAC"
    },
    {
      "pnr_number": "PNR100136",
      "name": "Ishaan Nair",
      "age": 28,
      "address": "Pune, India",
      "train_name": "Vande Bharat",
      "destination_station": "Chennai Central",
      "journey_date": "2026-04-07",
      "seat_number": "S2-65",
      "coach": "S2",
      "status": "Waiting"
    },
    {
      "pnr_number": "PNR100137",
      "name": "Swati Patel",
      "age": 64,
      "address": "Jaipur, India",
      "train_name": "Rajdhani Express",
      "destination_station": "New Delhi",
      "journey_date": "2026-04-08",
      "seat_number": "S3-66",
      "coach": "S3",
      "status": "Confirmed"
    },
    {
      "pnr_number": "PNR100138",
      "name": "Manav Ghosh",
      "age": 53,
      "address": "Bangalore, India",
      "train_name": "Duronto Express",
      "destination_station": "Mumbai Central",
      "journey_date": "2026-04-09",
      "seat_number": "S4-67",
      "coach": "S4",
      "status": "RAC"
    },
    {
      "pnr_number": "PNR100139",
      "name": "Aarav Nair",
      "age": 49,
      "address": "Jaipur, India",
      "train_name": "Shatabdi Express",
      "destination_station": "Chennai Central",
      "journey_date": "2026-04-10",
      "seat_number": "S5-68",
      "coach": "S5",
      "status": "Waiting"
    },
    {
      "pnr_number": "PNR100140",
      "name": "Meera Pandey",
      "age": 40,
      "address": "Ahmedabad, India",
      "train_name": "Vande Bharat",
      "destination_station": "Chennai Central",
      "journey_date": "2026-04-01",
      "seat_number": "S1-69",
      "coach": "S1",
      "status": "Waiting"
    },
    {
      "pnr_number": "PNR100141",
      "name": "Simran Verma",
      "age": 40,
      "address": "Delhi, India",
      "train_name": "Rajdhani Express",
      "destination_station": "Chennai Central",
      "journey_date": "2026-04-02",
      "seat_number": "S2-70",
      "coach": "S2",
      "status": "RAC"
    },
    {
      "pnr_number": "PNR100142",
      "name": "Parth Tiwari",
      "age": 50,
      "address": "Patna, India",
      "train_name": "Duronto Express",
      "destination_station": "Bangalore City",
      "journey_date": "2026-04-03",
      "seat_number": "S3-71",
      "coach": "S3",
      "status": "RAC"
    },
    {
      "pnr_number": "PNR100143",
      "name": "Arnav Mishra",
      "age": 49,
      "address": "Delhi, India",
      "train_name": "Shatabdi Express",
      "destination_station": "Chennai Central",
      "journey_date": "2026-04-04",
      "seat_number": "S4-72",
      "coach": "S4",
      "status": "Waiting"
    },
    {
      "pnr_number": "PNR100144",
      "name": "Simran Das",
      "age": 63,
      "address": "Chennai, India",
      "train_name": "Vande Bharat",
      "destination_station": "Howrah",
      "journey_date": "2026-04-05",
      "seat_number": "S5-1",
      "coach": "S5",
      "status": "Waiting"
    },
    {
      "pnr_number": "PNR100145",
      "name": "Arnav Gupta",
      "age": 23,
      "address": "Patna, India",
      "train_name": "Vande Bharat",
      "destination_station": "New Delhi",
      "journey_date": "2026-04-06",
      "seat_number": "S1-2",
      "coach": "S1",
      "status": "Waiting"
    },
    {
      "pnr_number": "PNR100146",
      "name": "Aditya Jain",
      "age": 30,
      "address": "Pune, India",
      "train_name": "Duronto Express",
      "destination_station": "New Delhi",
      "journey_date": "2026-04-07",
      "seat_number": "S2-3",
      "coach": "S2",
      "status": "Confirmed"
    },
    {
      "pnr_number": "PNR100147",
      "name": "Anjali Patel",
      "age": 35,
      "address": "Bangalore, India",
      "train_name": "Rajdhani Express",
      "destination_station": "Mumbai Central",
      "journey_date": "2026-04-08",
      "seat_number": "S3-4",
      "coach": "S3",
      "status": "Confirmed"
    },
    {
      "pnr_number": "PNR100148",
      "name": "Atharv Verma",
      "age": 50,
      "address": "Lucknow, India",
      "train_name": "Garib Rath",
      "destination_station": "New Delhi",
      "journey_date": "2026-04-09",
      "seat_number": "S4-5",
      "coach": "S4",
      "status": "Confirmed"
    },
    {
      "pnr_number": "PNR100149",
      "name": "Payal Menon",
      "age": 54,
      "address": "Bangalore, India",
      "train_name": "Garib Rath",
      "destination_station": "New Delhi",
      "journey_date": "2026-04-10",
      "seat_number": "S5-6",
      "coach": "S5",
      "status": "RAC"
    },
    {
      "pnr_number": "PNR100150",
      "name": "Kabir Mishra",
      "age": 36,
      "address": "Mumbai, India",
      "train_name": "Rajdhani Express",
      "destination_station": "Howrah",
      "journey_date": "2026-04-01",
      "seat_number": "S1-7",
      "coach": "S1",
      "status": "RAC"
    },
    {
      "pnr_number": "PNR100151",
      "name": "Kabir Patel",
      "age": 23,
      "address": "Chennai, India",
      "train_name": "Shatabdi Express",
      "destination_station": "Bangalore City",
      "journey_date": "2026-04-02",
      "seat_number": "S2-8",
      "coach": "S2",
      "status": "RAC"
    },
    {
      "pnr_number": "PNR100152",
      "name": "Ananya Roy",
      "age": 36,
      "address": "Patna, India",
      "train_name": "Rajdhani Express",
      "destination_station": "Mumbai Central",
      "journey_date": "2026-04-03",
      "seat_number": "S3-9",
      "coach": "S3",
      "status": "Confirmed"
    },
    {
      "pnr_number": "PNR100153",
      "name": "Shreya Yadav",
      "age": 58,
      "address": "Lucknow, India",
      "train_name": "Vande Bharat",
      "destination_station": "Bangalore City",
      "journey_date": "2026-04-04",
      "seat_number": "S4-10",
      "coach": "S4",
      "status": "RAC"
    },
    {
      "pnr_number": "PNR100154",
      "name": "Amit Mishra",
      "age": 36,
      "address": "Chennai, India",
      "train_name": "Shatabdi Express",
      "destination_station": "Bangalore City",
      "journey_date": "2026-04-05",
      "seat_number": "S5-11",
      "coach": "S5",
      "status": "Waiting"
    },
    {
      "pnr_number": "PNR100155",
      "name": "Muskan Reddy",
      "age": 45,
      "address": "Patna, India",
      "train_name": "Rajdhani Express",
      "destination_station": "Mumbai Central",
      "journey_date": "2026-04-06",
      "seat_number": "S1-12",
      "coach": "S1",
      "status": "RAC"
    },
    {
      "pnr_number": "PNR100156",
      "name": "Aarav Chauhan",
      "age": 48,
      "address": "Ahmedabad, India",
      "train_name": "Garib Rath",
      "destination_station": "Howrah",
      "journey_date": "2026-04-07",
      "seat_number": "S2-13",
      "coach": "S2",
      "status": "Waiting"
    },
    {
      "pnr_number": "PNR100157",
      "name": "Muskan Roy",
      "age": 32,
      "address": "Pune, India",
      "train_name": "Garib Rath",
      "destination_station": "Howrah",
      "journey_date": "2026-04-08",
      "seat_number": "S3-14",
      "coach": "S3",
      "status": "Confirmed"
    },
    {
      "pnr_number": "PNR100158",
      "name": "Neha Agarwal",
      "age": 40,
      "address": "Jaipur, India",
      "train_name": "Garib Rath",
      "destination_station": "New Delhi",
      "journey_date": "2026-04-09",
      "seat_number": "S4-15",
      "coach": "S4",
      "status": "RAC"
    },
    {
      "pnr_number": "PNR100159",
      "name": "Rudra Kumar",
      "age": 25,
      "address": "Kolkata, India",
      "train_name": "Rajdhani Express",
      "destination_station": "Bangalore City",
      "journey_date": "2026-04-10",
      "seat_number": "S5-16",
      "coach": "S5",
      "status": "RAC"
    },
    {
      "pnr_number": "PNR100160",
      "name": "Kartik Mishra",
      "age": 41,
      "address": "Ahmedabad, India",
      "train_name": "Garib Rath",
      "destination_station": "Bangalore City",
      "journey_date": "2026-04-01",
      "seat_number": "S1-17",
      "coach": "S1",
      "status": "RAC"
    },
    {
      "pnr_number": "PNR100161",
      "name": "Sneha Agarwal",
      "age": 54,
      "address": "Patna, India",
      "train_name": "Vande Bharat",
      "destination_station": "Chennai Central",
      "journey_date": "2026-04-02",
      "seat_number": "S2-18",
      "coach": "S2",
      "status": "Confirmed"
    },
    {
      "pnr_number": "PNR100162",
      "name": "Ananya Mishra",
      "age": 59,
      "address": "Lucknow, India",
      "train_name": "Garib Rath",
      "destination_station": "Howrah",
      "journey_date": "2026-04-03",
      "seat_number": "S3-19",
      "coach": "S3",
      "status": "Confirmed"
    },
    {
      "pnr_number": "PNR100163",
      "name": "Atharv Gupta",
      "age": 44,
      "address": "Delhi, India",
      "train_name": "Shatabdi Express",
      "destination_station": "Mumbai Central",
      "journey_date": "2026-04-04",
      "seat_number": "S4-20",
      "coach": "S4",
      "status": "Waiting"
    },
    {
      "pnr_number": "PNR100164",
      "name": "Rahul Das",
      "age": 22,
      "address": "Pune, India",
      "train_name": "Rajdhani Express",
      "destination_station": "Chennai Central",
      "journey_date": "2026-04-05",
      "seat_number": "S5-21",
      "coach": "S5",
      "status": "RAC"
    },
    {
      "pnr_number": "PNR100165",
      "name": "Yash Pandey",
      "age": 57,
      "address": "Patna, India",
      "train_name": "Duronto Express",
      "destination_station": "Mumbai Central",
      "journey_date": "2026-04-06",
      "seat_number": "S1-22",
      "coach": "S1",
      "status": "RAC"
    },
    {
      "pnr_number": "PNR100166",
      "name": "Tanvi Sharma",
      "age": 53,
      "address": "Patna, India",
      "train_name": "Duronto Express",
      "destination_station": "Bangalore City",
      "journey_date": "2026-04-07",
      "seat_number": "S2-23",
      "coach": "S2",
      "status": "RAC"
    },
    {
      "pnr_number": "PNR100167",
      "name": "Ishaan Pandey",
      "age": 49,
      "address": "Patna, India",
      "train_name": "Rajdhani Express",
      "destination_station": "New Delhi",
      "journey_date": "2026-04-08",
      "seat_number": "S3-24",
      "coach": "S3",
      "status": "Waiting"
    },
    {
      "pnr_number": "PNR100168",
      "name": "Dhruv Sharma",
      "age": 61,
      "address": "Lucknow, India",
      "train_name": "Duronto Express",
      "destination_station": "New Delhi",
      "journey_date": "2026-04-09",
      "seat_number": "S4-25",
      "coach": "S4",
      "status": "Confirmed"
    },
    {
      "pnr_number": "PNR100169",
      "name": "Amit Sharma",
      "age": 25,
      "address": "Chennai, India",
      "train_name": "Shatabdi Express",
      "destination_station": "Bangalore City",
      "journey_date": "2026-04-10",
      "seat_number": "S5-26",
      "coach": "S5",
      "status": "Confirmed"
    },
    {
      "pnr_number": "PNR100170",
      "name": "Kavya Tiwari",
      "age": 46,
      "address": "Ahmedabad, India",
      "train_name": "Duronto Express",
      "destination_station": "Chennai Central",
      "journey_date": "2026-04-01",
      "seat_number": "S1-27",
      "coach": "S1",
      "status": "Confirmed"
    },
    {
      "pnr_number": "PNR100171",
      "name": "Kartik Jain",
      "age": 30,
      "address": "Pune, India",
      "train_name": "Garib Rath",
      "destination_station": "Bangalore City",
      "journey_date": "2026-04-02",
      "seat_number": "S2-28",
      "coach": "S2",
      "status": "Confirmed"
    },
    {
      "pnr_number": "PNR100172",
      "name": "Meera Roy",
      "age": 49,
      "address": "Bangalore, India",
      "train_name": "Vande Bharat",
      "destination_station": "Chennai Central",
      "journey_date": "2026-04-03",
      "seat_number": "S3-29",
      "coach": "S3",
      "status": "Waiting"
    },
    {
      "pnr_number": "PNR100173",
      "name": "Aanya Sharma",
      "age": 58,
      "address": "Delhi, India",
      "train_name": "Duronto Express",
      "destination_station": "Bangalore City",
      "journey_date": "2026-04-04",
      "seat_number": "S4-30",
      "coach": "S4",
      "status": "Waiting"
    },
    {
      "pnr_number": "PNR100174",
      "name": "Nikhil Jain",
      "age": 57,
      "address": "Jaipur, India",
      "train_name": "Shatabdi Express",
      "destination_station": "Howrah",
      "journey_date": "2026-04-05",
      "seat_number": "S5-31",
      "coach": "S5",
      "status": "RAC"
    },
    {
      "pnr_number": "PNR100175",
      "name": "Shreya Patel",
      "age": 50,
      "address": "Delhi, India",
      "train_name": "Rajdhani Express",
      "destination_station": "Chennai Central",
      "journey_date": "2026-04-06",
      "seat_number": "S1-32",
      "coach": "S1",
      "status": "Confirmed"
    },
    {
      "pnr_number": "PNR100176",
      "name": "Tanvi Mishra",
      "age": 46,
      "address": "Chennai, India",
      "train_name": "Shatabdi Express",
      "destination_station": "New Delhi",
      "journey_date": "2026-04-07",
      "seat_number": "S2-33",
      "coach": "S2",
      "status": "Confirmed"
    },
    {
      "pnr_number": "PNR100177",
      "name": "Kavya Mishra",
      "age": 23,
      "address": "Delhi, India",
      "train_name": "Duronto Express",
      "destination_station": "New Delhi",
      "journey_date": "2026-04-08",
      "seat_number": "S3-34",
      "coach": "S3",
      "status": "Confirmed"
    },
    {
      "pnr_number": "PNR100178",
      "name": "Muhammad Verma",
      "age": 43,
      "address": "Kolkata, India",
      "train_name": "Vande Bharat",
      "destination_station": "New Delhi",
      "journey_date": "2026-04-09",
      "seat_number": "S4-35",
      "coach": "S4",
      "status": "Waiting"
    },
    {
      "pnr_number": "PNR100179",
      "name": "Muhammad Yadav",
      "age": 63,
      "address": "Ahmedabad, India",
      "train_name": "Garib Rath",
      "destination_station": "New Delhi",
      "journey_date": "2026-04-10",
      "seat_number": "S5-36",
      "coach": "S5",
      "status": "Waiting"
    },
    {
      "pnr_number": "PNR100180",
      "name": "Rahul Chauhan",
      "age": 30,
      "address": "Ahmedabad, India",
      "train_name": "Garib Rath",
      "destination_station": "New Delhi",
      "journey_date": "2026-04-01",
      "seat_number": "S1-37",
      "coach": "S1",
      "status": "Confirmed"
    },
    {
      "pnr_number": "PNR100181",
      "name": "Krishna Patel",
      "age": 50,
      "address": "Chennai, India",
      "train_name": "Vande Bharat",
      "destination_station": "Bangalore City",
      "journey_date": "2026-04-02",
      "seat_number": "S2-38",
      "coach": "S2",
      "status": "Waiting"
    },
    {
      "pnr_number": "PNR100182",
      "name": "Ishita Sharma",
      "age": 31,
      "address": "Mumbai, India",
      "train_name": "Rajdhani Express",
      "destination_station": "New Delhi",
      "journey_date": "2026-04-03",
      "seat_number": "S3-39",
      "coach": "S3",
      "status": "Confirmed"
    },
    {
      "pnr_number": "PNR100183",
      "name": "Meera Pandey",
      "age": 61,
      "address": "Patna, India",
      "train_name": "Vande Bharat",
      "destination_station": "Bangalore City",
      "journey_date": "2026-04-04",
      "seat_number": "S4-40",
      "coach": "S4",
      "status": "RAC"
    },
    {
      "pnr_number": "PNR100184",
      "name": "Muhammad Roy",
      "age": 25,
      "address": "Ahmedabad, India",
      "train_name": "Rajdhani Express",
      "destination_station": "New Delhi",
      "journey_date": "2026-04-05",
      "seat_number": "S5-41",
      "coach": "S5",
      "status": "RAC"
    },
    {
      "pnr_number": "PNR100185",
      "name": "Ishaan Nair",
      "age": 27,
      "address": "Mumbai, India",
      "train_name": "Vande Bharat",
      "destination_station": "Howrah",
      "journey_date": "2026-04-06",
      "seat_number": "S1-42",
      "coach": "S1",
      "status": "Confirmed"
    },
    {
      "pnr_number": "PNR100186",
      "name": "Sai Singh",
      "age": 46,
      "address": "Ahmedabad, India",
      "train_name": "Vande Bharat",
      "destination_station": "Howrah",
      "journey_date": "2026-04-07",
      "seat_number": "S2-43",
      "coach": "S2",
      "status": "Confirmed"
    },
    {
      "pnr_number": "PNR100187",
      "name": "Shaurya Roy",
      "age": 35,
      "address": "Lucknow, India",
      "train_name": "Rajdhani Express",
      "destination_station": "Mumbai Central",
      "journey_date": "2026-04-08",
      "seat_number": "S3-44",
      "coach": "S3",
      "status": "RAC"
    },
    {
      "pnr_number": "PNR100188",
      "name": "Meera Pandey",
      "age": 60,
      "address": "Lucknow, India",
      "train_name": "Vande Bharat",
      "destination_station": "New Delhi",
      "journey_date": "2026-04-09",
      "seat_number": "S4-45",
      "coach": "S4",
      "status": "RAC"
    },
    {
      "pnr_number": "PNR100189",
      "name": "Payal Agarwal",
      "age": 62,
      "address": "Chennai, India",
      "train_name": "Garib Rath",
      "destination_station": "Mumbai Central",
      "journey_date": "2026-04-10",
      "seat_number": "S5-46",
      "coach": "S5",
      "status": "Confirmed"
    },
    {
      "pnr_number": "PNR100190",
      "name": "Aditya Verma",
      "age": 59,
      "address": "Lucknow, India",
      "train_name": "Shatabdi Express",
      "destination_station": "Mumbai Central",
      "journey_date": "2026-04-01",
      "seat_number": "S1-47",
      "coach": "S1",
      "status": "RAC"
    },
    {
      "pnr_number": "PNR100191",
      "name": "Priya Das",
      "age": 26,
      "address": "Kolkata, India",
      "train_name": "Garib Rath",
      "destination_station": "Bangalore City",
      "journey_date": "2026-04-02",
      "seat_number": "S2-48",
      "coach": "S2",
      "status": "Confirmed"
    },
    {
      "pnr_number": "PNR100192",
      "name": "Vihaan Jain",
      "age": 63,
      "address": "Chennai, India",
      "train_name": "Rajdhani Express",
      "destination_station": "Howrah",
      "journey_date": "2026-04-03",
      "seat_number": "S3-49",
      "coach": "S3",
      "status": "RAC"
    },
    {
      "pnr_number": "PNR100193",
      "name": "Nisha Yadav",
      "age": 36,
      "address": "Patna, India",
      "train_name": "Shatabdi Express",
      "destination_station": "New Delhi",
      "journey_date": "2026-04-04",
      "seat_number": "S4-50",
      "coach": "S4",
      "status": "Confirmed"
    },
    {
      "pnr_number": "PNR100194",
      "name": "Samar Nair",
      "age": 23,
      "address": "Delhi, India",
      "train_name": "Duronto Express",
      "destination_station": "Mumbai Central",
      "journey_date": "2026-04-05",
      "seat_number": "S5-51",
      "coach": "S5",
      "status": "RAC"
    },
    {
      "pnr_number": "PNR100195",
      "name": "Yash Yadav",
      "age": 47,
      "address": "Delhi, India",
      "train_name": "Duronto Express",
      "destination_station": "Howrah",
      "journey_date": "2026-04-06",
      "seat_number": "S1-52",
      "coach": "S1",
      "status": "Waiting"
    },
    {
      "pnr_number": "PNR100196",
      "name": "Vivaan Ghosh",
      "age": 30,
      "address": "Mumbai, India",
      "train_name": "Garib Rath",
      "destination_station": "Mumbai Central",
      "journey_date": "2026-04-07",
      "seat_number": "S2-53",
      "coach": "S2",
      "status": "Confirmed"
    },
    {
      "pnr_number": "PNR100197",
      "name": "Ayush Verma",
      "age": 53,
      "address": "Pune, India",
      "train_name": "Rajdhani Express",
      "destination_station": "Bangalore City",
      "journey_date": "2026-04-08",
      "seat_number": "S3-54",
      "coach": "S3",
      "status": "RAC"
    },
    {
      "pnr_number": "PNR100198",
      "name": "Manav Agarwal",
      "age": 37,
      "address": "Kolkata, India",
      "train_name": "Duronto Express",
      "destination_station": "Bangalore City",
      "journey_date": "2026-04-09",
      "seat_number": "S4-55",
      "coach": "S4",
      "status": "Waiting"
    },
    {
      "pnr_number": "PNR100199",
      "name": "Vihaan Roy",
      "age": 63,
      "address": "Chennai, India",
      "train_name": "Rajdhani Express",
      "destination_station": "Bangalore City",
      "journey_date": "2026-04-10",
      "seat_number": "S5-56",
      "coach": "S5",
      "status": "RAC"
    }
  ]

  res.json(users);
});

//cors 
app.use(cors()) // frontend - http://localhost:3000/

// POST API (create user)
app.post("/users", (req, res) => {
  const newUser = req.body;
  res.json({
    message: "User created successfully",
     user: newUser
  });
});

// Start server
app.listen(PORT, () => {
  console.log(`Server running on http://127.0.0.1:3000/${PORT}`);
});